use_frameworks!
source 'https://github.com/jsonsnow/CLSpces.git'


platform :ios, '9.0'

target 'Mediator_Example' do
  pod 'Mediator', :path => '../'
  pod 'WGRouter'

  target 'Mediator_Tests' do
    inherit! :search_paths

    
  end
end
